# Site settings
title: "Junteng Liu"
email: jliugi@connect.ust.hk
description: >-
  First-year PhD candidate at HKUST NLP Group. Research focuses on natural
  language processing and machine learning.
baseurl: "/LJT-Homepage"
url: "https://atulinpj.github.io"

# Repository settings
repo: "atulinpj/LJT-Homepage"
github_username: "Vicent0205"
search: true

# Social media / academic profiles
twitter_username: "junteng88716710"
scholar_userid: "tbK9jl4AAAAJ"

# Site Author
author:
  name: "Junteng Liu"
  bio: >-
    First-year PhD candidate at HKUST NLP Group. Research focuses on natural
    language processing and machine learning.
  email: jliugi@connect.ust.hk
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:jliugi@connect.ust.hk"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Vicent0205"
    - label: "X (Twitter)"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://x.com/junteng88716710"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: /page:num/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Collections
collections:
  publications:
    output: true
    permalink: /publications/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "single"
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "single"

# Sass
sass:
  sass_dir: _sass
  style: compressed
